version: "3.7"

services: 
  proxy:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks: 
      - microfrontend
    ports:
      - ${PROXY_PORT}:80

  venda.frontend:
    build:
      context: ./src/frontend/venda
      dockerfile: prod/Dockerfile
      args: 
        - PUBLIC_URL=${VENDA_FRONTEND_PATH}
    networks: 
      - microfrontend
  
  atendimento.frontend:
    build:
      context: ./src/frontend/atendimento
      dockerfile: prod/Dockerfile
      args: 
        - PUBLIC_URL=${ATENDIMENTO_FRONTEND_PATH}
    networks: 
      - microfrontend

networks: 
  microfrontend:
    driver: bridge